name: Build & Release Docker

on:
  push:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      id: checkout
    - name: Set up JDK 1.8
      id: setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      id: build_maven
      run: ./mvnw -B package --file pom.xml
    - name: Docker Build (latest)
      id: docker_build_latest
      run: docker build -f src/main/docker/Dockerfile.jvm -t letsrokk/hello-world-challenge:latest .
    - name: Docker Build (versioned)
      id: docker_build_latest
      run: docker build -f src/main/docker/Dockerfile.jvm -t letsrokk/hello-world-challenge:${{ github.ref }} .
    - name: Docker Login
      id: docker_login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Docker Push (latest)
      id: docker_push_latest
      run: docker push letsrokk/hello-world-challenge:latest
    - name: Docker Push (versioned)
      id: docker_push_versioned
      run: docker push letsrokk/hello-world-challenge:${{ github.ref }}