name: Build & Test

on:
  push:
    branches:
      - master
      - branches/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      id: checkout
    - name: Set up JDK 1.8
      id: setup
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      id: build_maven
      run: ./mvnw -B clean test --file pom.xml
